FORMAT: 1A
HOST: http://api.fmomi.newway.pro/

# fmomis-api
Апи для мобильных приложений пациентов
API: ***api.fmomi.newway.pro***

# Перечисления

    ```java
    Gender {
        Male("М"),
        Female("Ж");
    }

    ConsultationState {
        NEW("Новая"),
        COMPLETED("Завершена"), 
        CANCELED("Отменена");
    }

    Authority {
        ADMIN("Администратор"), DOCTOR("Врач"), SUPERVISOR("Суперадминистратор"), PATIENT("Пациент"), CUSTOMER("Заказчик");
    }

    ParameterType {
        DIAGNOSIS("Диагноз"), TREATMENT_PLAN("План лечения"), RECOMMENDATIONS("Рекомендации"), RESEARCH_PLAN("План исследований");
    }

# Group Авторизация

## Авторизация [/api/auth/login?phone={phone}&password={password}]
### Получить доступ к мобильному приложению [POST]
+ Parameters
    + phone (required, string, `79655050288`) ... `phone` контактный телефонный номер пациента
    + password (required, string, `3890`) ... `пароль`полученный при регистрации или заполненный самостоятельно

+ Request
    
    + Headers

            X-API-VERSION: v1

+ Response 200 (application/json)

        {
           "success": true,
           "message": "Успешно получен sid",
            "sid":"fe99437d-4479-4c21-a979-110eed862fcb",
            "authorities": [PATIENT]
        }

## Проверка связи [/api/ping]
+ Request

+ Response 200 (application/json)

        {
           "success": true,
           "message": "PONG"
        }

## Регистрация пациента [/api/patient/auth/registration?phone={phone}]
### Запрос на отправку SMS [GET]
+ Parameters
    
    + phone (required, string, `79655050288`) ... `phone` контактный телефонный номер пациента

+ Request
    
    + Headers
                
            X-API-VERSION: v1


+ Response 200 (application/json)

        {
           "success": true,
           "message": "На ваш сотовый телефон отправлен временный пароль"
        }        

## Смена пароля пациента [/api/patient/password/?password={password}]
### Обновление пароля пациента [POST]

+ Parameters

    + password (required, string, `password`) ... `password` новое значение места работы

+ Request

    + Headers

            sid: {sid}
            X-API-VERSION: v1

+ Response 200 (application/json)

        {
            "success": true,
            "message": "Пароль изменен"
        } 
    

# Group Врач
## Регистрация врача [/api/doctor/auth/registration?phone={phone}]
### Запрос на отправку SMS [GET]
+ Parameters
    
    + phone (required, string, `79655050288`) ... `phone` контактный телефонный номер пациента

+ Request

    + Headers

            X-API-VERSION: v1

+ Response 200 (application/json)

        {
           "success": true,
           "message": "На ваш сотовый телефон отправлен временный пароль"
        }        

## Смена пароля врача [/api/doctor/password/?password={password}]
### Обновление пароля врача [POST]
+ Parameters
    + password (required, string, `password`) ... `password` новое значение места работы

+ Request (application/json)

    + Headers
    
            sid: {sid}
            X-API-VERSION: v1

+ Response 200 (application/json)

        {
            "success": true,
            "message": "Пароль изменен"
        } 

        
##Список пациентов [/api/doctor/patient?page={page}&size={size}]
###Прочитать список пациентов[GET]

+ Parameters

    + page (optional, integer) ... `page` номер страницы
    + size (optional, integer, `10`)

+ Request (application/json)

    + Headers
    
            X-API-VERSION: v1
            sid: {sid}

+ Response 200 (application/json)

        {
           "success": true,
           "message": "Список пациентов успешно прочитан!",
           "count":" 10,
           "patients": [{
              "id": 1,
              "phone": "79021234567"
           },
           {
              "id": 2,
              "phone": "79021234567"
           },
           {
              "id": 3,
              "phone": "79021234567"
           },
           {
              "id": 4,
              "phone": "79021234567"
           }]
        }

### Создать нового пациента[POST]
+ Request (application/json)

    + Headers

            X-API-VERSION: v1
            sid: {sid}
    + Body
    
            {
                  "phone": "79021234567"
            }

+ Response 200 (application/json)
            
        {
            "success" : true,
            "message" : "Пациент успешно создан!",
            "patient" : {
                "id" : 1,
                "phone" : "79021234567",
                "num" : 1 //Номер карточки
            }
        }

## Поиск пациентов по номеру или части первой части номера телефона [/api/doctor/patient/search/{phone}?page={page}&size={size}]
### Найти пациентов по номеру или части первой части номера телефона [GET]
+ Parameters

    + page (optional, integer) ... `page` номер страницы
    + size (optional, integer, `10`)
    + phone (required, string) 

+ Request (application/json)

    + Headers
    
            X-API-VERSION: v1
            sid: {sid}
    
+ Response 200 (application/json)

        {
           "success": true,
           "message": "Список пациентов успешно прочитан!",
           "count": 10,
           "patients": [{
              "id": 1,
              "phone": "79021234567"
           },
           {
              "id": 2,
              "phone": "79021234567"
           },
           {
              "id": 3,
              "phone": "79021234567"
           },
           {
              "id": 4,
              "phone": "79021234567"
           }]
        }


# Раздел шаблоны [/api/doctor/template/{id}]

### Чтение шаблона[GET]

+ Request (application/json)

    + Headers
    
            X-API-VERSION: v1
            sid: {sid}
        
+ Response 200 (application/json) 

        {
            "id": 1,
            "title": "ОРЗ",
            "visitAt": "2015-03-05T17:06:00.000+0500",
            "state": "COMPLETED",
            "diagnostics": "Ветрянка",
            "treatmentPlan": [{
                id: 1,
                title: "Левофлоксацин (Сигницеф,Л-оптик,Офтаквикс)",
                plan: "1 к х 8 раз в день в оба глаза -3 дня,затем 1 к х 4 разав день - 4 дня"                
            }],
            "researchPlan": "Сдать анализы. Анализы принимаются по будням",
            "recommendations": "Рекомендация 1: 456: 789: 123"            
        }

### Чтение списка шаблонов [/api/doctor/template]

+ Request (application/json)

    + Headers
            
            X-API-VERSION: v1
            sid: {sid}
            
+ Response 200 (application/json) 

        {
            "success": true,
            "message": "Шаблон консультации создан!",
            "templates": [{
                "id": 1,
                "title": "ОРЗ",
                "visitAt": "2015-03-05T17:06:00.000+0500",
                "state": "COMPLETED",
                "diagnostics": "Ветрянка",
                "treatmentPlan": [{
                    id: 1,
                    title: "Левофлоксацин (Сигницеф,Л-оптик,Офтаквикс)",
                    plan: "1 к х 8 раз в день в оба глаза -3 дня,затем 1 к х 4 разав день - 4 дня"                
                }],
                "researchPlan": "Сдать анализы. Анализы принимаются по будням",
                "recommendations": "Рекомендация 1: 456: 789: 123"            
            }]
        }

###Создания шаблона врача[POST]
+ Request (application/json)

    + Headers

            X-API-VERSION: v1
            sid: {sid}

    + Body            

            {
                "id": 1,
                "title": "ОРЗ",
                "visitAt": "2015-03-05T17:06:00.000+0500",
                "state": "COMPLETED",
                "diagnostics": "Ветрянка",
                "treatmentPlan": [{
                    id: 1,
                    title: "Левофлоксацин (Сигницеф,Л-оптик,Офтаквикс)",
                    plan: "1 к х 8 раз в день в оба глаза -3 дня,затем 1 к х 4 разав день - 4 дня"                
                }],
                "researchPlan": "Сдать анализы. Анализы принимаются по будням",
                "recommendations": "Рекомендация 1: 456: 789: 123"            
            }
        
+ Response 200 (application/json)

        {
            "success": true,
            "message": "Шаблон консультации создан!",
            "template": {
                "id": 1,
                "title": "ОРЗ",
                "visitAt": "2015-03-05T17:06:00.000+0500",
                "state": "COMPLETED",
                "diagnostics": "Ветрянка",
                "treatmentPlan": [{
                    id: 1,
                    title: "Левофлоксацин (Сигницеф,Л-оптик,Офтаквикс)",
                    plan: "1 к х 8 раз в день в оба глаза -3 дня,затем 1 к х 4 разав день - 4 дня"                
                }],
                "researchPlan": "Сдать анализы. Анализы принимаются по будням",
                "recommendations": "Рекомендация 1: 456: 789: 123"            
            }
        }

# Раздел консультаций [/api/doctor/consultation]
## Консультации пациента у врача [/api/doctor/consultation?page={page}&size={size}]
### Чтение списка консультаций врача[GET]
+ Parameters

    + page (optional, integer) ... `page` номер страницы
    + size (optional, integer, `10`)

+ Request (application/json)

    + Headers
            
            X-API-VERSION: v1
            sid: {sid}

+ Response 200 (application/json)

        {
           "success": true,
           "message": "Список консультаций успешно прочитан!",
           "consultations": [{
              "id": 1,
              "visitAt": "2015-03-05T17:06:00.000+0500",
              "state": "COMPLETED",
              "diagnostics": "Ветрянка",
              "treatmentPlan": [{
                id: 1,
                title: "Левофлоксацин (Сигницеф,Л-оптик,Офтаквикс)",
                plan: "1 к х 8 раз в день в оба глаза -3 дня,затем 1 к х 4 разав день - 4 дня"                
              }],
              "researchPlan": "Сдать анализы. Анализы принимаются по будням",
              "status": "Консультация",
              "recommendations": "Рекомендация 1: 456: 789: 123",
              "employee":          {
                    "id": 1,
                    "phone": "79021234567",
                    "employeeType":             {
                        "id": "54bf2007ce9c157100783655",
                        "name": "Терапевт"
                    }
                },
              "price" : 305.12
           },
           {
              "id": 2,
              "visitAt": "2015-03-05T17:06:00.000+0500",
              "state": "COMPLETED",
              "diagnostics": "Мракобесие",
              "treatmentPlan": [{
                id: 1,
                title: "Левофлоксацин (Сигницеф,Л-оптик,Офтаквикс)",
                plan: "1 к х 8 раз в день в оба глаза -3 дня,затем 1 к х 4 разав день - 4 дня"                
              }],
              "researchPlan": "Сдать анализы. Анализы принимаются по будням",
              "status": "Окуривание",
              "recommendations": "Рекомендация 1: 456: 789: 123",
              "employee":          {
                    "id": 1,
                    "phone": "79021234567",
                    "employeeType":             {
                        "id": "54bf2007ce9c157100783655",
                        "name": "Шаман"
                    }
                },
              "price" : 300
           },
           {
              "id": 3,
              "visitAt": "2015-03-05T17:06:00.000+0500",
              "state": "COMPLETED",
              "diagnostics": "ОРВИ",
              "treatmentPlan": [{
                id: 1,
                title: "Левофлоксацин (Сигницеф,Л-оптик,Офтаквикс)",
                plan: "1 к х 8 раз в день в оба глаза -3 дня,затем 1 к х 4 разав день - 4 дня"                
              }],
              "researchPlan": "Сдать анализы. Анализы принимаются по будням",
              "status": "Консультация",
              "recommendations": "Рекомендация 1: 456: 789: 123",
              "employee":          {
                    "id": 1,
                    "phone": "79021234567",
                    "employeeType":             {
                        "id": "54bf2007ce9c157100783655",
                        "name": "Терапевт"
                    }
                },
              "price" : 128.5
           },
           {
              "id": 4,
              "visitAt": "2015-03-05T17:06:00.000+0500",
              "state": "COMPLETED",
              "diagnostics": "Неведомая ерунда",
              "treatmentPlan": [{
                id: 1,
                title: "Левофлоксацин (Сигницеф,Л-оптик,Офтаквикс)",
                plan: "1 к х 8 раз в день в оба глаза -3 дня,затем 1 к х 4 разав день - 4 дня"                
              },
              {
                id: 2,
                title: "Test-huest",
                plan: "1 к х 8 раз в день в оба глаза -3 дня,затем 1 к х 4 разав день - 4 дня"                
              }],
              "researchPlan": "Сдать анализы. Анализы принимаются по будням",
              "status": "Выписка",
              "recommendations": "Рекомендация 1: 456: 789: 123",
              "employee":          {
                    "id": 1,
                    "phone": "79021234567",
                    "employeeType":             {
                        "id": "54bf2007ce9c157100783655",
                        "name": "Специалист по неведомой ерунде"
                    }
                },
              "price" : 512
           }
           ]
        }

### Создание консультаций врача[POST]
+ Request (application/json)

    + Headers
            
            X-API-VERSION: v1
            sid: {sid}
    + Body
    
            {
              "patient" : {
                    "id" : 1
              },
              "state": "COMPLETED",
              "diagnosis": "Ветрянка",
              "treatmentPlan": [{
                id: 1,
                plan: "1 к х 8 раз в день в оба глаза -3 дня,затем 1 к х 4 разав день - 4 дня"                
              }],
              "researchPlan": "Сдать анализы. Анализы принимаются по будням",
              "status": "Консультация",
              "recommendations": "Рекомендация 1: 456: 789: 123"
            }    

+ Response 200 (application/json)

        {
           "success": true,
           "message": "Список консультаций успешно прочитан!",
           "count": "10",
           "consultation": {
              "id": 1,
              "visitAt": "2015-03-05T17:06:00.000+0500",
              "state": "COMPLETED",
              "diagnosis": "Ветрянка",
              "treatmentPlan": [{
                id: 1,
                title: "Левофлоксацин (Сигницеф,Л-оптик,Офтаквикс)",
                plan: "1 к х 8 раз в день в оба глаза -3 дня,затем 1 к х 4 разав день - 4 дня"                
              }],
              "researchPlan": "Сдать анализы. Анализы принимаются по будням",
              "status": "Консультация",
              "recommendations": "Рекомендация 1: 456: 789: 123",
              "patient":          {
                    "id": 1,
                    "phone": "79021234567"
                },
              "price" : 305.12
           }
        }

        
## Консультаця пациента у врача [/api/doctor/consultation/{id}]
### Чтение консультации пациента у врача [GET]
+ Parameters

    + id (required, integer) ... `id` идентификатор консультации

+ Request (application/json)
    
    + Headers
            
            X-API-VERSION: v1
            sid: {sid}

+ Response 200 (application/json)

        {
           "success": true,
           "message": "Список консультаций успешно прочитан!",
           "consultation": {
              "id": 1,
              "visitAt": "2015-03-05T17:06:00.000+0500",
              "state": "COMPLETED",
              "diagnostics": "Ветрянка",
              "treatmentPlan": [{
                id: 1,
                title: "Левофлоксацин (Сигницеф,Л-оптик,Офтаквикс)",
                plan: "1 к х 8 раз в день в оба глаза -3 дня,затем 1 к х 4 разав день - 4 дня"                
              }],
              "researchPlan": "Сдать анализы. Анализы принимаются по будням",
              "status": "Консультация",
              "recommendations": "Рекомендация 1: 456: 789: 123",
              "patient":          {
                    "id": 1,
                    "phone": "79021234567",
              },
              "price" : 305.12
           }
        }

# Параметры [/api/doctor/parameter/{ParameterType}]
## Поиск параметра [/api/doctor/parameter/{ParameterType}?search={search}&page={page}&size={size}]
### Найти параметр [GET]

+ Parameters

    + ParameterType (required, ParameterType)
    + search (optional, string)
    + page (optional, integer) ... `page` номер страницы
    + size (optional, integer, `10`)

+ Request (application/json)

    + Headers
            
            X-API-VERSION: v1
            sid: {sid}

+ Response 200 (application/json)

        {
           "success": true,
           "message": "Список параметров успешно прочитан!",
           "count": 5,
           "parameters": [{
              "id": 1,
              "title": "Левофлоксацин (Сигницеф,Л-оптик,Офтаквикс)"
           },
           {
              "id": 2,
              "title": "Левофлоксацин (Сигницеф,Л-оптик,Офтаквикс)"
           },
           {
              "id": 3,
              "title": "Левофлоксацин (Сигницеф,Л-оптик,Офтаквикс)"
           },
           {
              "id": 4,
              "title": "Левофлоксацин (Сигницеф,Л-оптик,Офтаквикс)"
           }]
        }

# Group Консультации Пациента
## Консультации пациента [/api/patient/consultation?page={page}&size={size}]
### Получение списка консультаций пациента [GET]

+ Parameters

    + page (optional, integer) ... `page` номер страницы
    + size (optional, integer, `10`)

+ Request (application/json)

    + Headers
            
            X-API-VERSION: v1
            sid: {sid}

+ Response 200 (application/json)

        {
           "success": true,
           "message": "Список консультаций успешно прочитан!",
           "count": 5,
           "consultations": [{
              "id": 1,
              "visitAt": "2015-03-05T17:06:00.000+0500",
              "state": "COMPLETED",
              "diagnostics": "Ветрянка",
              "treatmentPlan": [{
                id: 1,
                title: "Левофлоксацин (Сигницеф,Л-оптик,Офтаквикс)",
                plan: "1 к х 8 раз в день в оба глаза -3 дня,затем 1 к х 4 разав день - 4 дня"                
              }],
              "researchPlan": "Сдать анализы. Анализы принимаются по будням",
              "status": "Консультация",
              "recommendations": "Рекомендация 1: 456: 789: 123",
              "employee":          {
                    "id": 1,
                    "phone": "79021234567",
                    "employeeType":             {
                        "id": "54bf2007ce9c157100783655",
                        "name": "Терапевт"
                    }
                },
              "price" : 305.12
           },
           {
              "id": 2,
              "visitAt": "2015-03-05T17:06:00.000+0500",
              "state": "COMPLETED",
              "diagnostics": "Мракобесие",
              "treatmentPlan": [{
                id: 1,
                title: "Левофлоксацин (Сигницеф,Л-оптик,Офтаквикс)",
                plan: "1 к х 8 раз в день в оба глаза -3 дня,затем 1 к х 4 разав день - 4 дня"                
              }],
              "researchPlan": "Сдать анализы. Анализы принимаются по будням",
              "status": "Окуривание",
              "recommendations": "Рекомендация 1: 456: 789: 123",
              "employee":          {
                    "id": 1,
                    "phone": "79021234567",
                    "employeeType":             {
                        "id": "54bf2007ce9c157100783655",
                        "name": "Шаман"
                    }
                },
              "price" : 300
           },
           {
              "id": 3,
              "visitAt": "2015-03-05T17:06:00.000+0500",
              "state": "COMPLETED",
              "diagnostics": "ОРВИ",
              "treatmentPlan": [{
                id: 1,
                title: "Левофлоксацин (Сигницеф,Л-оптик,Офтаквикс)",
                plan: "1 к х 8 раз в день в оба глаза -3 дня,затем 1 к х 4 разав день - 4 дня"                
              }],
              "researchPlan": "Сдать анализы. Анализы принимаются по будням",
              "status": "Консультация",
              "recommendations": "Рекомендация 1: 456: 789: 123",
              "employee":          {
                    "id": 1,
                    "phone": "79021234567",
                    "employeeType":             {
                        "id": "54bf2007ce9c157100783655",
                        "name": "Терапевт"
                    }
                },
              "price" : 128.5
           },
           {
              "id": 4,
              "visitAt": "2015-03-05T17:06:00.000+0500",
              "state": "COMPLETED",
              "diagnostics": "Неведомая ерунда",
              "treatmentPlan": [{
                id: 1,
                title: "Левофлоксацин (Сигницеф,Л-оптик,Офтаквикс)",
                plan: "1 к х 8 раз в день в оба глаза -3 дня,затем 1 к х 4 разав день - 4 дня"                
              },
              {
                id: 2,
                title: "Test-huest",
                plan: "1 к х 8 раз в день в оба глаза -3 дня,затем 1 к х 4 разав день - 4 дня"                
              }],
              "researchPlan": "Сдать анализы. Анализы принимаются по будням",
              "status": "Выписка",
              "recommendations": "Рекомендация 1: 456: 789: 123",
              "employee":          {
                    "id": 1,
                    "phone": "79021234567",
                    "employeeType":             {
                        "id": "54bf2007ce9c157100783655",
                        "name": "Специалист по неведомой ерунде"
                    }
                },
              "price" : 512
           }
           ]
        }

## Консультация пациента [/api/patient/consultation/{id}]
### Чтение консультации [GET]

+ Parameters

    + id (required, integer, `1`)

+ Request (application/json)

    + Headers

            X-API-VERSION: v1
            sid: {sid}

+ Response 200 (application/json)

        {
           "success": true,
           "message": "Карточка консультации прочитана успешно!",
           "consultation":    {
              "id": 1,
              "visitAt": "2015-03-06T16:21:00.000+0500",
              "state": "COMPLETED",
              "diagnostics": "Ветрянка",
              "treatmentPlan": [{
                id: 1,
                title: "Левофлоксацин (Сигницеф,Л-оптик,Офтаквикс)",
                plan: "1 к х 8 раз в день в оба глаза -3 дня,затем 1 к х 4 разав день - 4 дня"                
              }],
              "researchPlan": "",
              "status": "Консультация",
              "recommendations": "Рекомендация 1: 456: 789: 123",
              "employee":          {
                    "id": 1,
                    "phone": "79021234567",
                    "employeeType":             {
                        "id": "54bf2007ce9c157100783655",
                        "name": "терапевт ревматолог"
                    }
                }
           }
        }
        
## Аптека [/api/pharmacy/{id}]
### Чтение цен на лекарства [GET]

+ Parameters

    + id (required, integer, `1`) ... идентификатор консультации

+ Request (application/json)

    + Headers

            X-API-VERSION: v1
            sid: {sid}

+ Response 200 (application/json)

        {
               "success": true,
               "message": "Цены прочитаны успешно!",
               "pharmacy": [{
                  "id": 1,
                  "title" : "Живика",
                  "address": "Город екатеринбург, Ленина 105",
                  "fullprice": 171.16,
                  "medicines": [{
                    "id":1,
                    "title": "Левофлоксацин (Сигницеф,Л-оптик,Офтаквикс)",
                    "form": "90 таблеток по 50мг",
                    "price": 159.16 //копейки???
                  },
                  {"id":2,
                    "title": "Подорожник",
                    "form": "50 листочков по 1",
                    "price": 12
                  }]
               },
               {
                  "id": 2,
                  "title" : "36,6",
                  "address": "Город екатеринбург, Ленина 101",
                  "fullprice": 337.87,
                  "medicines": [{
                    "id":1,
                    "title": "Левофлоксацин (Сигницеф,Л-оптик,Офтаквикс)",
                    "form": "90 таблеток по 50мг",
                    "price": 142.12
                  },
                  {"id":2,
                    "title": "Подорожник",
                    "form": "50 листочков по 1",
                    "price": 10
                  },
                  {"id":3,
                    "title": "Амбробене",
                    "form": "150 мл",
                    "price": 185.75
                  }]
               }]
        }
    
### Размещение заявки на лекарства [POST]
+ Parameters

    + id (required, integer, `1`) ... идентификатор консультации

+ Request (application/json)

    + Headers

            X-API-VERSION: v1
            sid: {sid}

    + Body
    
            {
                  "id": 1, // идентификатор аптеки
            } 

+ Response 200 (application/json)

        {
               "success": true,
               "message": "Заказ успешно размещен. Ожидайте звонка",
        }