FORMAT: 1A
HOST: http://api.fmomi.newway.pro/

# fmomis-api
Апи для мобильных приложений пациентов
API: ***api.fmomi.newway.pro***

# Перечисления

    ```java
    Gender {
        Male("М"),
        Female("Ж");
    }

    ConsultationState {
        NEW("Новая"),
        COMPLETED("Завершена"), 
        CANCELED("Отменена");
    }


# Group Авторизация

## Проверка связи [/api/ping]
+ Request

+ Response 200 (application/json)

        {
           "success": true,
           "message": "PONG"
        }
        
## Регистрация пациента [/api/patient/auth/registration?phone={phone}]
### Запрос на отправку SMS [GET]
+ Parameters
    + phone (required, string, `79655050288`) ... `phone` контактный телефонный номер пациента

+ Request
    + Headers
        X-API-VERSION: v1

+ Response 200 (application/json)
        {
           "success": true,
           "message": "На ваш сотовый телефон отправлен временный пароль"
        }        

## Авторизация пациента [/api/auth/login?phone={phone}&password={password}]
### Получить доступ к мобильному приложению [POST]
+ Parameters
    + phone (required, string, `79655050288`) ... `phone` контактный телефонный номер пациента
    + password (required, string, `3890`) ... `пароль`полученный при регистрации или заполненный самостоятельно

+ Request
    
    + Headers

            X-API-VERSION: v1

+ Response 200 (application/json)

        {
           "success": true,
           "message": "Успешно получен sid",
            "sid":"fe99437d-4479-4c21-a979-110eed862fcb"
        }
        
## Смена пароля пациента [/api/patient/password/?password={password}]
### Обновление пароля пациента [POST]

+ Parameters

    + password (required, string, `password`) ... `password` новое значение места работы

+ Request (application/json)

    + Headers
    
            sid: {sid}
            X-API-VERSION: v1

+ Response 200 (application/json)
        {
            "success": true,
            "message": "Пароль изменен"
        } 

#Group Врач

## Регистрация врача [/api/doctor/auth/registration?phone={phone}]
### Запрос на отправку SMS [GET]
+ Parameters
    + phone (required, string, `79655050288`) ... `phone` контактный телефонный номер пациента

+ Request
    + Headers
        X-API-VERSION: v1

+ Response 200 (application/json)
        {
           "success": true,
           "message": "На ваш сотовый телефон отправлен временный пароль"
        }        

## Смена пароля врача [/api/doctor/password/?password={password}]
### Обновление пароля пациента [POST]

+ Parameters

    + password (required, string, `password`) ... `password` новое значение места работы

+ Request (application/json)

    + Headers
    
            sid: {sid}
            X-API-VERSION: v1

+ Response 200 (application/json)
        {
            "success": true,
            "message": "Пароль изменен"
        } 

        
##Список последних консультаций [/api/doctor/patient?page={page}&size={size}]
###Прочитать список последних консультаций[GET]

+ Parameters

    + page (optional, integer) ... `page` номер страницы
    + size (optional, integer, `10`)
    
+ Request (application/json)

    + Headers
            
            X-API-VERSION: v1
            sid: {sid}

+ Response 200 (application/json)

        {
           "success": true,
           "message": "Список консультаций успешно прочитан!",
           "patients": [{
              "id": 1,
              "visitAt": "2015-03-05T17:06:00.000+0500",
              "phone": "79022623586"
           },
           {
              "id": 2,
              "visitAt": "2015-03-05T17:06:00.000+0500",
              "phone": "79022623586"
           }]
        }

    
#Раздел шаблоны

##Шаблоны врача[/api/doctor/template/{id}]

###Чтение шаблонов[GET]
+ Parameters

    + Headers
            
            X-API-VERSION: v1
            sid: {sid}

+ Request (application/json)

    + Headers
            
            X-API-VERSION: v1
            sid: {sid}
+ Response 200 (application/json) 

        {
            "id": 1,
            "title": "ОРЗ",
            "visitAt": "2015-03-05T17:06:00.000+0500",
            "state": "COMPLETED",
            "diagnostics": "Ветрянка",
            "treatmentPlan": [{
                id: 1,
                title: "Левофлоксацин (Сигницеф,Л-оптик,Офтаквикс)",
                plan: "1 к х 8 раз в день в оба глаза -3 дня,затем 1 к х 4 разав день - 4 дня"                
            }],
            "researchPlan": "Сдать анализы. Анализы принимаются по будням",
            "recommendations": "Рекомендация 1: 456: 789: 123"            
        }

##Шаблоны врача[/api/doctor/template]
###Чтение списка шаблонов[GET]

+ Parameters

    + Headers
            
            X-API-VERSION: v1
            sid: {sid}

+ Request (application/json)

    + Headers
            
            X-API-VERSION: v1
            sid: {sid}
            
+ Response 200 (application/json) 

        {
            "success": true,
            "message": "Шаблон консультации создан!",
            "templates": [{
                "id": 1,
                "title": "ОРЗ",
                "visitAt": "2015-03-05T17:06:00.000+0500",
                "state": "COMPLETED",
                "diagnostics": "Ветрянка",
                "treatmentPlan": [{
                    id: 1,
                    title: "Левофлоксацин (Сигницеф,Л-оптик,Офтаквикс)",
                    plan: "1 к х 8 раз в день в оба глаза -3 дня,затем 1 к х 4 разав день - 4 дня"                
                }],
                "researchPlan": "Сдать анализы. Анализы принимаются по будням",
                "recommendations": "Рекомендация 1: 456: 789: 123"            
            }]
        }

###Создания шаблона врача[POST]
+ Parameters
    + Headers
            
            X-API-VERSION: v1
            sid: {sid}

+ Request (application/json)
    + Method 
            POST
    + Headers
            
            X-API-VERSION: v1
            sid: {sid}

        {
            "id": 1,
            "title": "ОРЗ",
            "visitAt": "2015-03-05T17:06:00.000+0500",
            "state": "COMPLETED",
            "diagnostics": "Ветрянка",
            "treatmentPlan": [{
                id: 1,
                title: "Левофлоксацин (Сигницеф,Л-оптик,Офтаквикс)",
                plan: "1 к х 8 раз в день в оба глаза -3 дня,затем 1 к х 4 разав день - 4 дня"                
            }],
            "researchPlan": "Сдать анализы. Анализы принимаются по будням",
            "recommendations": "Рекомендация 1: 456: 789: 123"            
        }
        
+ Response 200 (application/json)

        {
            "success": true,
            "message": "Шаблон консультации создан!",
            "template": {
                "id": 1,
                "title": "ОРЗ",
                "visitAt": "2015-03-05T17:06:00.000+0500",
                "state": "COMPLETED",
                "diagnostics": "Ветрянка",
                "treatmentPlan": [{
                    id: 1,
                    title: "Левофлоксацин (Сигницеф,Л-оптик,Офтаквикс)",
                    plan: "1 к х 8 раз в день в оба глаза -3 дня,затем 1 к х 4 разав день - 4 дня"                
                }],
                "researchPlan": "Сдать анализы. Анализы принимаются по будням",
                "recommendations": "Рекомендация 1: 456: 789: 123"            
            }
        }

#Раздел консультаций

## Консультации пациента у врача[/api/doctor/consultation/{id}]
+ Parameters

    + id (required, integer) ... `id` идентификатор консультации

+ Request (application/json)
    + Headers
            
            X-API-VERSION: v1
            sid: {sid}

+ Response 200 (application/json)

        {
           "success": true,
           "message": "Список консультаций успешно прочитан!",
           "consultation": {
              "id": 1,
              "visitAt": "2015-03-05T17:06:00.000+0500",
              "state": "COMPLETED",
              "diagnostics": "Ветрянка",
              "treatmentPlan": [{
                id: 1,
                title: "Левофлоксацин (Сигницеф,Л-оптик,Офтаквикс)",
                plan: "1 к х 8 раз в день в оба глаза -3 дня,затем 1 к х 4 разав день - 4 дня"                
              }],
              "researchPlan": "Сдать анализы. Анализы принимаются по будням",
              "status": "Консультация",
              "recommendations": "Рекомендация 1: 456: 789: 123",
              "employee":          {
                    "id": 1,
                    "phone": "79021234567",
                    "employeeType":             {
                        "id": "54bf2007ce9c157100783655",
                        "name": "Терапевт"
                    }
                },
              "price" : 305.12
           }
        }

# Group Консультации Пациента
## Консультации пациента [/api/patient/consultation?page={page}&size={size}]
### Получение списка консультаций пациента [GET]

+ Parameters

    + page (optional, integer) ... `page` номер страницы
    + size (optional, integer, `10`)

+ Request (application/json)

    + Headers
            
            X-API-VERSION: v1
            sid: {sid}

+ Response 200 (application/json)

        {
           "success": true,
           "message": "Список консультаций успешно прочитан!",
           "nextId": 5,
           "consultations": [{
              "id": 1,
              "visitAt": "2015-03-05T17:06:00.000+0500",
              "state": "COMPLETED",
              "diagnostics": "Ветрянка",
              "treatmentPlan": [{
                id: 1,
                title: "Левофлоксацин (Сигницеф,Л-оптик,Офтаквикс)",
                plan: "1 к х 8 раз в день в оба глаза -3 дня,затем 1 к х 4 разав день - 4 дня"                
              }],
              "researchPlan": "Сдать анализы. Анализы принимаются по будням",
              "status": "Консультация",
              "recommendations": "Рекомендация 1: 456: 789: 123",
              "employee":          {
                    "id": 1,
                    "phone": "79021234567",
                    "employeeType":             {
                        "id": "54bf2007ce9c157100783655",
                        "name": "Терапевт"
                    }
                },
              "price" : 305.12
           },
           {
              "id": 2,
              "visitAt": "2015-03-05T17:06:00.000+0500",
              "state": "COMPLETED",
              "diagnostics": "Мракобесие",
              "treatmentPlan": [{
                id: 1,
                title: "Левофлоксацин (Сигницеф,Л-оптик,Офтаквикс)",
                plan: "1 к х 8 раз в день в оба глаза -3 дня,затем 1 к х 4 разав день - 4 дня"                
              }],
              "researchPlan": "Сдать анализы. Анализы принимаются по будням",
              "status": "Окуривание",
              "recommendations": "Рекомендация 1: 456: 789: 123",
              "employee":          {
                    "id": 1,
                    "phone": "79021234567",
                    "employeeType":             {
                        "id": "54bf2007ce9c157100783655",
                        "name": "Шаман"
                    }
                },
              "price" : 300
           },
           {
              "id": 3,
              "visitAt": "2015-03-05T17:06:00.000+0500",
              "state": "COMPLETED",
              "diagnostics": "ОРВИ",
              "treatmentPlan": [{
                id: 1,
                title: "Левофлоксацин (Сигницеф,Л-оптик,Офтаквикс)",
                plan: "1 к х 8 раз в день в оба глаза -3 дня,затем 1 к х 4 разав день - 4 дня"                
              }],
              "researchPlan": "Сдать анализы. Анализы принимаются по будням",
              "status": "Консультация",
              "recommendations": "Рекомендация 1: 456: 789: 123",
              "employee":          {
                    "id": 1,
                    "phone": "79021234567",
                    "employeeType":             {
                        "id": "54bf2007ce9c157100783655",
                        "name": "Терапевт"
                    }
                },
              "price" : 128.5
           },
           {
              "id": 4,
              "visitAt": "2015-03-05T17:06:00.000+0500",
              "state": "COMPLETED",
              "diagnostics": "Неведомая ерунда",
              "treatmentPlan": [{
                id: 1,
                title: "Левофлоксацин (Сигницеф,Л-оптик,Офтаквикс)",
                plan: "1 к х 8 раз в день в оба глаза -3 дня,затем 1 к х 4 разав день - 4 дня"                
              },
              {
                id: 2,
                title: "Test-huest",
                plan: "1 к х 8 раз в день в оба глаза -3 дня,затем 1 к х 4 разав день - 4 дня"                
              }],
              "researchPlan": "Сдать анализы. Анализы принимаются по будням",
              "status": "Выписка",
              "recommendations": "Рекомендация 1: 456: 789: 123",
              "employee":          {
                    "id": 1,
                    "phone": "79021234567",
                    "employeeType":             {
                        "id": "54bf2007ce9c157100783655",
                        "name": "Специалист по неведомой ерунде"
                    }
                },
              "price" : 512
           }
           ]
        }

## Консультация пациента [/api/patient/consultation/{id}]
### Чтение консультации [GET]

+ Parameters

    + sid (required, string, `00000000-0000-0000-0000-000000000000`) ... `sid` Ключ полученный при авторизаци
    + id (required, integer, `1`)

+ Request (application/json)

    + Headers

            X-API-VERSION: v1
            sid: {sid}

+ Response 200 (application/json)

        {
           "success": true,
           "message": "Карточка консультации прочитана успешно!",
           "consultation":    {
              "id": 1,
              "visitAt": "2015-03-06T16:21:00.000+0500",
              "state": "COMPLETED",
              "diagnostics": "Ветрянка",
              "treatmentPlan": [{
                id: 1,
                title: "Левофлоксацин (Сигницеф,Л-оптик,Офтаквикс)",
                plan: "1 к х 8 раз в день в оба глаза -3 дня,затем 1 к х 4 разав день - 4 дня"                
              }],
              "researchPlan": "",
              "status": "Консультация",
              "recommendations": "Рекомендация 1: 456: 789: 123",
              "employee":          {
                    "id": 1,
                    "phone": "79021234567",
                    "employeeType":             {
                        "id": "54bf2007ce9c157100783655",
                        "name": "терапевт ревматолог"
                    }
                }
           }
        }
        
## Аптека [/api/pharmacy/{id}]
### Чтение цен на лекарства [GET]

+ Parameters

    + sid (required, string, `00000000-0000-0000-0000-000000000000`) ... `sid` Ключ полученный при авторизаци
    + id (required, integer, `1`) ... идентификатор консультации

+ Request (application/json)

    + Headers

            X-API-VERSION: v1
            sid: {sid}

+ Response 200 (application/json)

        {
               "success": true,
               "message": "Цены прочитаны успешно!",
               "pharmacy": [{
                  "id": 1,
                  "title" : "Живика",
                  "address": "Город екатеринбург, Ленина 105",
                  "fullprice": 171.16,
                  "medicines": [{
                    "id":1,
                    "title": "Левофлоксацин (Сигницеф,Л-оптик,Офтаквикс)",
                    "form": "90 таблеток по 50мг",
                    "price": 159.16 //копейки???
                  },
                  {"id":2,
                    "title": "Подорожник",
                    "form": "50 листочков по 1",
                    "price": 12
                  }]
               },
               {
                  "id": 2,
                  "title" : "36,6",
                  "address": "Город екатеринбург, Ленина 101",
                  "fullprice": 337.87,
                  "medicines": [{
                    "id":1,
                    "title": "Левофлоксацин (Сигницеф,Л-оптик,Офтаквикс)",
                    "form": "90 таблеток по 50мг",
                    "price": 142.12
                  },
                  {"id":2,
                    "title": "Подорожник",
                    "form": "50 листочков по 1",
                    "price": 10
                  },
                  {"id":3,
                    "title": "Амбробене",
                    "form": "150 мл",
                    "price": 185.75
                  }]
               }]
        }
    
### Размещение заявки на лекарства [POST]
+ Parameters

    + sid (required, string, `00000000-0000-0000-0000-000000000000`) ... `sid` Ключ полученный при авторизаци
    + id (required, integer, `1`) ... идентификатор консультации

+ Request (application/json)

    + Headers

            X-API-VERSION: v1
            sid: {sid}

    {
          "id": 1, // идентификатор аптеки
    } 

+ Response 200 (application/json)

        {
               "success": true,
               "message": "Заказ успешно размещен. Ожидайте звонка",
        }