FORMAT: 1A
HOST: http://api.fmomi.newway.pro/

# fmomis-api
Апи для мобильных приложений пациентов
API: ***api.fmomi.newway.pro***

# Перечисления

    ```java
    Gender {
        Male("М"),
        Female("Ж");
    }

    ConsultationState {
        NEW("Новая"),
        COMPLETED("Завершена"), 
        CANCELED("Отменена");
    }

    Authority {
        ADMIN("Администратор"), DOCTOR("Врач"), SUPERVISOR("Суперадминистратор"), PATIENT("Пациент"), CUSTOMER("Заказчик");
    }

    ParameterType {
        DIAGNOSIS("Диагноз"), TREATMENT_PLAN("План лечения"), RECOMMENDATIONS("Рекомендации"), RESEARCH_PLAN("План исследований");
    }

    OrderState {
        NEW("Новый"), SENT("Отправлен"), ACCEPTED("Подтвержден"), REJECTED("Отклонен"), COLLECTED("Заказ собран"), COMPLETED("Заказ передан клиенту");
    }
    
    DeviceType {
        ANDROID("Андроид");
    }

# Group Авторизация

## Авторизация [/api/auth/login?phone={phone}&password={password}&role={role}]
### Получить доступ к мобильному приложению [POST]
+ Parameters
    + phone (required, string, `79655050288`) ... `phone` контактный телефонный номер пациента
    + password (required, string, `3890`) ... `пароль`полученный при регистрации или заполненный самостоятельно
    + role (optional, Authority, `PATIENT`) ... Роль под которой авторизуется пользователь

+ Request
    
    + Headers

            X-API-VERSION: v1

+ Response 200 (application/json)

        {
           "success": true,
           "message": "Успешно получен sid",
            "sid":"fe99437d-4479-4c21-a979-110eed862fcb",
            "authorities": [PATIENT]
        }

## Проверка связи [/api/ping]
+ Request

+ Response 200 (application/json)

        {
           "success": true,
           "message": "PONG"
        }

## Регистрация пациента [/api/patient/auth/registration?phone={phone}]
### Запрос на отправку SMS [GET]
+ Parameters
    
    + phone (required, string, `79655050288`) ... `phone` контактный телефонный номер пациента

+ Request
    
    + Headers
                
            X-API-VERSION: v1


+ Response 200 (application/json)

        {
           "success": true,
           "message": "На ваш сотовый телефон отправлен временный пароль"
        }        

## Данные пациента [/api/patient]
### Чтение данных пациента [GET]

+ Request

    + Headers

            sid: {sid}
            X-API-VERSION: v1

+ Response 200 (application/json)

        {
            "patient": {
                "id": 1,
                "name": "name",
                "phone": "71234567891"
                "address": "address",
                "job": "job",
                "birthDate": "2015-03-05T17:06:00.000+0500",
                "deviceType": "ANDROID", //DeviceType
                "pushToken": "blabla"
            },
            "success": true,
            "message": "Данные о пациенте успешно прочитаны"
        } 

### Обновление данных пациента [POST]

+ Request

    + Headers

            sid: {sid}
            X-API-VERSION: v1

    + Body

            {
              "name": "name",
              "address": "address",
              "job": "job",
              "birthDate": "2015-03-05T17:06:00.000+0500",
              "deviceType": "ANDROID", //DeviceType
              "pushToken": "blabla"
            }
        
+ Response 200 (application/json)

        {
            "patient": {
                "name": "name",
                "address": "address",
                "job": "job",
                "birthDate": "2015-03-05T17:06:00.000+0500",
                "deviceType": "ANDROID", //DeviceType
                "pushToken": "blabla"                
            },
            "success": true,
            "message": "Данные о пациенте успешно обновлены"
        } 

## Данные пациента [/api/patient/diagnoses]
### Чтение данных пациента [GET]

+ Request

    + Headers

            sid: {sid}
            X-API-VERSION: v1

+ Response 200 (application/json)

        {
            "diagnoses" : ["ОРЗ", "Воспаление уха"],
            "success": true,
            "message": "Данные о диагнозах успешно прочитаны"
        } 

## Данные пациента [/api/patient/doctors]
### Чтение данных пациента [GET]

+ Request

    + Headers

            sid: {sid}
            X-API-VERSION: v1

+ Response 200 (application/json)

        {
            "doctors" : [
                {
                    "id": 1,
                    "name" : "Вася пупкин",
                    "position":             {
                        "id": 1,
                        "name": "Терапевт"
                    }
                }, 
                {
                    "id": 2,
                    "name" : "Иванов Иван",
                    "position":             {
                        "id": 1,
                        "name": "Хирург"
                    }
                }],
            "success": true,
            "message": "Данные о врачах успешно прочитаны"
        } 

## Смена пароля пациента [/api/patient/password/?password={password}]
### Обновление пароля пациента [POST]

+ Parameters

    + password (required, string, `password`) ... `password` новое значение места работы

+ Request

    + Headers

            sid: {sid}
            X-API-VERSION: v1

+ Response 200 (application/json)

        {
            "success": true,
            "message": "Пароль изменен"
        } 
    

# Group Врач
## Регистрация врача [/api/doctor/auth/registration?phone={phone}]
### Запрос на отправку SMS [GET]
+ Parameters
    
    + phone (required, string, `79655050288`) ... `phone` контактный телефонный номер пациента

+ Request

    + Headers

            X-API-VERSION: v1

+ Response 200 (application/json)

        {
           "success": true,
           "message": "На ваш сотовый телефон отправлен временный пароль"
        }        

## Смена пароля врача [/api/doctor/password/?password={password}]
### Обновление пароля врача [POST]
+ Parameters
    + password (required, string, `password`) ... `password` новое значение места работы

+ Request (application/json)

    + Headers
    
            sid: {sid}
            X-API-VERSION: v1

+ Response 200 (application/json)

        {
            "success": true,
            "message": "Пароль изменен"
        } 

        
##Список пациентов [/api/doctor/patient?page={page}&size={size}]
###Прочитать список пациентов[GET]

+ Parameters

    + page (optional, integer) ... `page` номер страницы
    + size (optional, integer, `10`)

+ Request (application/json)

    + Headers
    
            X-API-VERSION: v1
            sid: {sid}

+ Response 200 (application/json)

        {
           "success": true,
           "message": "Список пациентов успешно прочитан!",
           "count":" 10,
           "patients": [{
              "id": 1,
              "phone": "79021234567"
           },
           {
              "id": 2,
              "phone": "79021234567"
           },
           {
              "id": 3,
              "phone": "79021234567"
           },
           {
              "id": 4,
              "phone": "79021234567"
           }]
        }

### Создать нового пациента[POST]
+ Request (application/json)

    + Headers

            X-API-VERSION: v1
            sid: {sid}
    + Body
    
            {
                  "phone": "79021234567"
            }

+ Response 200 (application/json)
            
        {
            "success" : true,
            "message" : "Пациент успешно создан!",
            "patient" : {
                "id" : 1,
                "phone" : "79021234567",
                "num" : 1 //Номер карточки
            }
        }

## Поиск пациентов по номеру или части первой части номера телефона [/api/doctor/patient/search/{phone}?page={page}&size={size}]
### Найти пациентов по номеру или части первой части номера телефона [GET]
+ Parameters

    + page (optional, integer) ... `page` номер страницы
    + size (optional, integer, `10`)
    + phone (required, string) 

+ Request (application/json)

    + Headers
    
            X-API-VERSION: v1
            sid: {sid}
    
+ Response 200 (application/json)

        {
           "success": true,
           "message": "Список пациентов успешно прочитан!",
           "count": 10,
           "patients": [{
              "id": 1,
              "phone": "79021234567"
           },
           {
              "id": 2,
              "phone": "79021234567"
           },
           {
              "id": 3,
              "phone": "79021234567"
           },
           {
              "id": 4,
              "phone": "79021234567"
           }]
        }
# Подтверждение оферты врачем [/api/doctor/accept]

+ Request (application/json)

    + Headers
    
            X-API-VERSION: v1
            sid: {sid}

+ Response 200 (application/json) 

        {
            "bankСard": "123456",
            "certificate": "1234123",
            "offerAccepted": true,
            "medicalFacility": [
                {
                    "id": 1,
                    "title": "Учреждение 1"
                },
                {
                    "id": 2,
                    "title": "Учреждение 2"
                }
            ],
            "specialisations": [
                {
                    "id": 1,
                    "title": "Уролог"
                }
            ]
        }

# Раздел карточка врача [/api/doctor]
### Чтение карточки[GET]

+ Request (application/json)

    + Headers
    
            X-API-VERSION: v1
            sid: {sid}

+ Response 200 (application/json) 

        {
            "bankСard": "123456",
            "certificate": "1234123",
            "offerAccepted": true,
            "license": "1234",
            "name": "Name",
            "phone": "79022623586",
            "medicalFacility": [
                {
                    "id": 1,
                    "title": "Учреждение 1"
                },
                {
                    "id": 2,
                    "title": "Учреждение 2"
                }
            ],
            "specialisations": [
                {
                    "id": 1,
                    "title": "Уролог"
                }
            ]
        }

### Обновление карточки[POST]

+ Request (application/json)

    + Headers
    
            X-API-VERSION: v1
            sid: {sid}
            
    + Body
    
            {
                "bankСard": "123456",
                "certificate": "1234123",
                "offerAccepted": true,
                "license": "1234",
                "name": "Name",
                "phone": "79022623586",                
                "medicalFacility": [
                    {
                        "id": 1,
                        "title": "Учреждение 1"
                    },
                    {
                        "id": 2,
                        "title": "Учреждение 2"
                    }
                ],
                "specialisations": [
                    {
                        "id": 1,
                        "title": "Уролог"
                    }
                ]
            }

+ Response 200 (application/json) 

        {
            "bankСard": "123456",
            "certificate": "1234123",
            "offerAccepted": true,
            "license": "1234",
            "name": "Name",
            "phone": "79022623586",            
            "medicalFacility": [
                {
                    "id": 1,
                    "title": "Учреждение 1"
                },
                {
                    "id": 2,
                    "title": "Учреждение 2"
                }
            ],
            "specialisations": [
                {
                    "id": 1,
                    "title": "Уролог"
                }
            ]
        }

# Раздел шаблоны [/api/doctor/template/{id}]

### Чтение шаблона[GET]
+ Parameters

    + id (required, integer) 
    
+ Request (application/json)

    + Headers
    
            X-API-VERSION: v1
            sid: {sid}
        
+ Response 200 (application/json) 

        {
            "id": 1,
            "title": "ОРЗ",
            "visitAt": "2015-03-05T17:06:00.000+0500",
            "state": "COMPLETED",
            "diagnosis": "Ветрянка",
            "treatmentPlan": [{
                "id": 1,
                "title": "Левофлоксацин (Сигницеф,Л-оптик,Офтаквикс)",
                "plan": "1 к х 8 раз в день в оба глаза -3 дня,затем 1 к х 4 разав день - 4 дня"                
            }],
            "researchPlan": "Сдать анализы. Анализы принимаются по будням",
            "recommendations": "Рекомендация 1: 456: 789: 123"            
        }

### Обновление шаблона[PUT]
+ Parameters

    + id (optional, integer) 
    
+ Request (application/json)

    + Headers

            X-API-VERSION: v1
            sid: {sid}
        
+ Request

    + Body
        
            {
                "id": 1,
                "title": "ОРЗ",
                "visitAt": "2015-03-05T17:06:00.000+0500",
                "state": "COMPLETED",
                "diagnosis": "Ветрянка",
                "treatmentPlan": [{
                    "id": 1,
                    "title": "Левофлоксацин (Сигницеф,Л-оптик,Офтаквикс)",
                    "plan": "1 к х 8 раз в день в оба глаза -3 дня,затем 1 к х 4 разав день - 4 дня"                
                }],
                "researchPlan": "Сдать анализы. Анализы принимаются по будням",
                "recommendations": "Рекомендация 1: 456: 789: 123"            
            }

+ Response 200 (application/json) 

        {
            "id": 1,
            "title": "ОРЗ",
            "visitAt": "2015-03-05T17:06:00.000+0500",
            "state": "COMPLETED",
            "diagnosis": "Ветрянка",
            "treatmentPlan": [{
                "id": 1,
                "title": "Левофлоксацин (Сигницеф,Л-оптик,Офтаквикс)",
                "plan": "1 к х 8 раз в день в оба глаза -3 дня,затем 1 к х 4 разав день - 4 дня"                
            }],
            "researchPlan": "Сдать анализы. Анализы принимаются по будням",
            "recommendations": "Рекомендация 1: 456: 789: 123"            
        }
        
###Удаление шаблона врача [DELETE]

+ Parameters

    + id (required, integer) 
    
+ Request (application/json)

    + Headers

            X-API-VERSION: v1
            sid: {sid}

+ Response 200 (application/json)

        {
            "success": true,
            "message": "Шаблон консультации удален!",
        }
        
### Чтение списка шаблонов [/api/doctor/template?page={page}&size={size}]

+ Request (application/json)
    + Parameters
        + page (optional, integer) ... `page` номер страницы
        + size (optional, integer, `10`)
        
    + Headers
            
            X-API-VERSION: v1
            sid: {sid}
            
+ Response 200 (application/json) 

        {
            "success": true,
            "message": "Шаблон консультации создан!",
            "templates": [{
                "id": 1,
                "title": "ОРЗ",
                "visitAt": "2015-03-05T17:06:00.000+0500",
                "state": "COMPLETED",
                "diagnosis": "Ветрянка",
                "treatmentPlan": [{
                    "id": 1,
                    "title": "Левофлоксацин (Сигницеф,Л-оптик,Офтаквикс)",
                    "plan": "1 к х 8 раз в день в оба глаза -3 дня,затем 1 к х 4 разав день - 4 дня"                
                }],
                "researchPlan": "Сдать анализы. Анализы принимаются по будням",
                "recommendations": "Рекомендация 1: 456: 789: 123"            
            }]
        }

###Создание шаблона врача [POST]

+ Request (application/json)

    + Headers

            X-API-VERSION: v1
            sid: {sid}

    + Body            

            {
                "title": "ОРЗ",
                "visitAt": "2015-03-05T17:06:00.000+0500",
                "state": "COMPLETED",
                "diagnosis": "Ветрянка",
                "treatmentPlan": [{
                    "parameterId": 1,
                    "title": "Левофлоксацин (Сигницеф,Л-оптик,Офтаквикс)",
                    "plan": "1 к х 8 раз в день в оба глаза -3 дня,затем 1 к х 4 разав день - 4 дня"                
                }],
                "researchPlan": "Сдать анализы. Анализы принимаются по будням",
                "recommendations": "Рекомендация 1: 456: 789: 123"            
            }
        
+ Response 200 (application/json)

        {
            "success": true,
            "message": "Шаблон консультации создан!",
            "template": {
                "id": 1,
                "title": "ОРЗ",
                "visitAt": "2015-03-05T17:06:00.000+0500",
                "state": "COMPLETED",
                "diagnosis": "Ветрянка",
                "treatmentPlan": [{
                    "id": 1,
                    "title": "Левофлоксацин (Сигницеф,Л-оптик,Офтаквикс)",
                    "plan": "1 к х 8 раз в день в оба глаза -3 дня,затем 1 к х 4 разав день - 4 дня"                
                }],
                "researchPlan": "Сдать анализы. Анализы принимаются по будням",
                "recommendations": "Рекомендация 1: 456: 789: 123"            
            }
        }

###Поиск шаблона врача [/api/doctor/template/search?search={search}&page={page}&size={size}]
+ Request (application/json)
    + Parameters
        + search (optional, integer) ... `search` начальная часть заголовка шаблона
        + page (optional, integer) ... `page` номер страницы
        + size (optional, integer, `10`)
    + Headers

            X-API-VERSION: v1
            sid: {sid}

+ Response 200 (application/json)

        {
            "success": true,
            "message": "Шаблоны консультации успешно прочитаны!",
            "templates": [{
                "id": 1,
                "title": "ОРЗ",
                "visitAt": "2015-03-05T17:06:00.000+0500",
                "state": "COMPLETED",
                "diagnosis": "Ветрянка",
                "treatmentPlan": [{
                    "id": 1,
                    "title": "Левофлоксацин (Сигницеф,Л-оптик,Офтаквикс)",
                    "plan": "1 к х 8 раз в день в оба глаза -3 дня,затем 1 к х 4 разав день - 4 дня"                
                }],
                "researchPlan": "Сдать анализы. Анализы принимаются по будням",
                "recommendations": "Рекомендация 1: 456: 789: 123"            
            }]
        }

# Раздел консультаций [/api/doctor/consultation]
## Консультации пациентов у врача [/api/doctor/consultation?page={page}&size={size}]
### Чтение списка консультаций врача[GET]
+ Parameters

    + page (optional, integer) ... `page` номер страницы
    + size (optional, integer, `10`)

+ Request (application/json)

    + Headers
            
            X-API-VERSION: v1
            sid: {sid}

+ Response 200 (application/json)

        {
           "success": true,
           "message": "Список консультаций успешно прочитан!",
           "consultations": [{
              "id": 1,
              "visitAt": "2015-03-05T17:06:00.000+0500",
              "nextVisitAt": "2015-03-06T17:06:00.000+0500",
              "state": "COMPLETED",
              "diagnosis": "Ветрянка",
              "treatmentPlan": [{
                "id": 1,
                "title": "Левофлоксацин (Сигницеф,Л-оптик,Офтаквикс)",
                "plan": "1 к х 8 раз в день в оба глаза -3 дня,затем 1 к х 4 разав день - 4 дня"                
              }],
              "researchPlan": "Сдать анализы. Анализы принимаются по будням",
              "researchData": "bla bla bla",
              "status": "Консультация",
              "recommendations": "Рекомендация 1: 456: 789: 123",
              "employee":          {
                    "id": 1,
                    "phone": "79021234567",
                    "position":             {
                        "id": 1,
                        "name": "Терапевт"
                    }
                },
              "price" : 305.12
           },
           {
              "id": 2,
              "visitAt": "2015-03-05T17:06:00.000+0500",
              "nextVisitAt": "2015-03-06T17:06:00.000+0500",
              "state": "COMPLETED",
              "diagnosis": "Мракобесие",
              "treatmentPlan": [{
                "id": 1,
                "title": "Левофлоксацин (Сигницеф,Л-оптик,Офтаквикс)",
                "plan": "1 к х 8 раз в день в оба глаза -3 дня,затем 1 к х 4 разав день - 4 дня"                
              }],
              "researchPlan": "Сдать анализы. Анализы принимаются по будням",
              "researchData": "bla bla bla",
              "status": "Окуривание",
              "recommendations": "Рекомендация 1: 456: 789: 123",
              "employee":          {
                    "id": 1,
                    "phone": "79021234567",
                    "position":             {
                        "id": 1,
                        "name": "Шаман"
                    }
                },
              "price" : 300
           },
           {
              "id": 3,
              "visitAt": "2015-03-05T17:06:00.000+0500",
              "nextVisitAt": "2015-03-06T17:06:00.000+0500",
              "state": "COMPLETED",
              "diagnosis": "ОРВИ",
              "treatmentPlan": [{
                "id": 1,
                "title": "Левофлоксацин (Сигницеф,Л-оптик,Офтаквикс)",
                "plan": "1 к х 8 раз в день в оба глаза -3 дня,затем 1 к х 4 разав день - 4 дня"                
              }],
              "researchPlan": "Сдать анализы. Анализы принимаются по будням",
              "researchData": "bla bla bla",
              "status": "Консультация",
              "recommendations": "Рекомендация 1: 456: 789: 123",
              "employee":          {
                    "id": 1,
                    "phone": "79021234567",
                    "position":             {
                        "id": 1,
                        "name": "Терапевт"
                    }
                },
              "price" : 128.5
           },
           {
              "id": 4,
              "visitAt": "2015-03-05T17:06:00.000+0500",
              "nextVisitAt": "2015-03-06T17:06:00.000+0500",
              "state": "COMPLETED",
              "diagnosis": "Неведомая ерунда",
              "treatmentPlan": [{
                "id": 1,
                "title": "Левофлоксацин (Сигницеф,Л-оптик,Офтаквикс)",
                "plan": "1 к х 8 раз в день в оба глаза -3 дня,затем 1 к х 4 разав день - 4 дня"                
              },
              {
                "id": 2,
                "title": "Test-huest",
                "plan": "1 к х 8 раз в день в оба глаза -3 дня,затем 1 к х 4 разав день - 4 дня"                
              }],
              "researchPlan": "Сдать анализы. Анализы принимаются по будням",
              "researchData": "bla bla bla",
              "status": "Выписка",
              "recommendations": "Рекомендация 1: 456: 789: 123",
              "employee":          {
                    "id": 1,
                    "phone": "79021234567",
                    "position":             {
                        "id": 1,
                        "name": "Специалист по неведомой ерунде"
                    }
                },
              "price" : 512
           }
           ]
        }

### Создание консультаций врача[POST]
+ Request (application/json)

    + Headers
            
            X-API-VERSION: v1
            sid: {sid}
    + Body
    
            {
              "patient" : {
                    "id" : 1
              },
              "state": "COMPLETED",
              "visitAt": "2015-03-05T17:06:00.000+0500",
              "nextVisitAt": "2015-03-06T17:06:00.000+0500",
              "diagnosis": "Ветрянка",
              "treatmentPlan": [{
                "parameterId": 1,
                "plan": "1 к х 8 раз в день в оба глаза -3 дня,затем 1 к х 4 разав день - 4 дня"                
              }],
              "researchPlan": "Сдать анализы. Анализы принимаются по будням",
              "researchData": "bla bla bla",
              "status": "Консультация",
              "recommendations": "Рекомендация 1: 456: 789: 123"
            }    

+ Response 200 (application/json)

        {
           "success": true,
           "message": "Список консультаций успешно прочитан!",
           "count": "10",
           "consultation": {
              "id": 1,
              "visitAt": "2015-03-05T17:06:00.000+0500",
              "nextVisitAt": "2015-03-06T17:06:00.000+0500",
              "state": "COMPLETED",
              "diagnosis": "Ветрянка",
              "treatmentPlan": [{
                "id": 1,
                "parameterId" : 1,
                "title": "Левофлоксацин (Сигницеф,Л-оптик,Офтаквикс)",
                "plan": "1 к х 8 раз в день в оба глаза -3 дня,затем 1 к х 4 разав день - 4 дня"                
              }],
              "researchPlan": "Сдать анализы. Анализы принимаются по будням",
              "researchData": "bla bla bla",
              "status": "Консультация",
              "recommendations": "Рекомендация 1: 456: 789: 123",
              "patient":          {
                    "id": 1,
                    "phone": "79021234567"
                },
              "price" : 305.12
           }
        }

        
## Консультаця врача [/api/doctor/consultation/{id}]
### Чтение консультации врача [GET]
+ Parameters

    + id (required, integer) ... `id` идентификатор консультации

+ Request (application/json)
    
    + Headers
            
            X-API-VERSION: v1
            sid: {sid}

+ Response 200 (application/json)

        {
           "success": true,
           "message": "Список консультаций успешно прочитан!",
           "consultation": {
              "id": 1,
              "visitAt": "2015-03-05T17:06:00.000+0500",
              "nextVisitAt": "2015-03-06T17:06:00.000+0500",
              "state": "COMPLETED",
              "diagnosis": "Ветрянка",
              "treatmentPlan": [{
                "id": 1,
                "title": "Левофлоксацин (Сигницеф,Л-оптик,Офтаквикс)",
                "plan": "1 к х 8 раз в день в оба глаза -3 дня,затем 1 к х 4 разав день - 4 дня"                
              }],
              "researchPlan": "Сдать анализы. Анализы принимаются по будням",
              "researchData": "bla bla bla",
              "status": "Консультация",
              "recommendations": "Рекомендация 1: 456: 789: 123",
              "patient":          {
                    "id": 1,
                    "phone": "79021234567",
              },
              "price" : 305.12
           }
        }
        
### Обновление консультации врача [PUT]

+ Request (application/json)

    + Headers
            
            X-API-VERSION: v1
            sid: {sid}
    + Body
    
            {
              "state": "COMPLETED",
              "visitAt": "2015-03-05T17:06:00.000+0500",
              "nextVisitAt": "2015-03-06T17:06:00.000+0500",
              "diagnosis": "Ветрянка",
              "treatmentPlan": [{
                "parameterId": 1,
                "plan": "1 к х 8 раз в день в оба глаза -3 дня,затем 1 к х 4 разав день - 4 дня"                
              }],
              "researchPlan": "Сдать анализы. Анализы принимаются по будням",
              "researchData": "bla bla bla",
              "status": "Консультация",
              "recommendations": "Рекомендация 1: 456: 789: 123"
            }    

+ Response 200 (application/json)

        {
           "success": true,
           "message": "Консультация обновлена!",
           "count": "10",
           "consultation": {
              "id": 1,
              "visitAt": "2015-03-05T17:06:00.000+0500",
              "nextVisitAt": "2015-03-06T17:06:00.000+0500",
              "state": "COMPLETED",
              "diagnosis": "Ветрянка",
              "treatmentPlan": [{
                "id": 1,
                "title": "Левофлоксацин (Сигницеф,Л-оптик,Офтаквикс)",
                "plan": "1 к х 8 раз в день в оба глаза -3 дня,затем 1 к х 4 разав день - 4 дня"                
              }],
              "researchPlan": "Сдать анализы. Анализы принимаются по будням",
              "researchData": "bla bla bla",
              "status": "Консультация",
              "recommendations": "Рекомендация 1: 456: 789: 123",
              "patient":          {
                    "id": 1,
                    "phone": "79021234567"
                },
              "price" : 305.12
           }
        }

## Консультации пациента врача [/api/doctor/consultation/patient/{id}?page={page}&size={size}]
### Чтение консультаций пациента врача [GET]
+ Parameters

    + id (required, integer) ... `id` идентификатор пациента
    + page (optional, integer) ... `page` номер страницы
    + size (optional, integer, `10`)

+ Request (application/json)
    
    + Headers
            
            X-API-VERSION: v1
            sid: {sid}

+ Response 200 (application/json)

        {
           "success": true,
           "message": "Список консультаций успешно прочитан!",
           "count": 1,
           "consultations": [{
              "id": 1,
              "visitAt": "2015-03-05T17:06:00.000+0500",
              "nextVisitAt": "2015-03-06T17:06:00.000+0500",
              "state": "COMPLETED",
              "diagnosis": "Ветрянка",
              "treatmentPlan": [{
                "id": 1,
                "title": "Левофлоксацин (Сигницеф,Л-оптик,Офтаквикс)",
                "plan": "1 к х 8 раз в день в оба глаза -3 дня,затем 1 к х 4 разав день - 4 дня"                
              }],
              "researchPlan": "Сдать анализы. Анализы принимаются по будням",
              "researchData": "bla bla bla",
              "status": "Консультация",
              "recommendations": "Рекомендация 1: 456: 789: 123",
              "patient":          {
                    "id": 1,
                    "phone": "79021234567",
              },
              "price" : 305.12
           }]
        }

# Параметры [/api/doctor/parameter/{ParameterType}]
## Поиск параметра [/api/doctor/parameter/{ParameterType}?search={search}&page={page}&size={size}]
### Найти параметр [GET]

+ Parameters

    + ParameterType (required, ParameterType)
    + search (optional, string)
    + page (optional, integer) ... `page` номер страницы
    + size (optional, integer, `10`)

+ Request (application/json)

    + Headers
            
            X-API-VERSION: v1
            sid: {sid}

+ Response 200 (application/json)

        {
           "success": true,
           "message": "Список параметров успешно прочитан!",
           "count": 5,
           "parameters": [{
              "id": 1,
              "title": "Левофлоксацин (Сигницеф,Л-оптик,Офтаквикс)"
           },
           {
              "id": 2,
              "title": "Левофлоксацин (Сигницеф,Л-оптик,Офтаквикс)"
           },
           {
              "id": 3,
              "title": "Левофлоксацин (Сигницеф,Л-оптик,Офтаквикс)"
           },
           {
              "id": 4,
              "title": "Левофлоксацин (Сигницеф,Л-оптик,Офтаквикс)"
           }]
        }

##Список заказов [/api/doctor/pharmacy?page={page}&size={size}]
###Прочитать список пациентов[GET]

+ Parameters

    + page (optional, integer) ... `page` номер страницы
    + size (optional, integer, `10`)

+ Request (application/json)

    + Headers
    
            X-API-VERSION: v1
            sid: {sid}

+ Response 200 (application/json)

        [{
                    "id" : 1,
                    "state" : "NEW",//OrderState
                    "createdAt" : '2015-03-05T17:06:00.000+0500',
                    "num": "1-1",
                    "prices" : [
                        {
                            "id":1,
                            "title": "Левофлоксацин (Сигницеф,Л-оптик,Офтаквикс)",
                            "form": "90 таблеток по 50мг",
                            "price": 14212, //в копейках
                            "amount":1
                        },
                        {
                            "id":2,
                            "title": "Подорожник",
                            "form": "50 листочков по 1",
                            "price":, 1000 //в копейках
                            "amount":1
                        },
                        {
                            "id":3,
                            "title": "Амбробене",
                            "form": "150 мл",
                            "price": 18575, //в копейках
                            "amount":1
                        }                    
                    ]
        }]

# Group Консультации Пациента
## Консультации пациента [/api/patient/consultation?page={page}&size={size}]
### Получение списка консультаций пациента [GET]

+ Parameters

    + page (optional, integer) ... `page` номер страницы
    + size (optional, integer, `10`)

+ Request (application/json)

    + Headers
            
            X-API-VERSION: v1
            sid: {sid}

+ Response 200 (application/json)

        {
           "success": true,
           "message": "Список консультаций успешно прочитан!",
           "count": 5,
           "consultations": [{
              "id": 1,
              "visitAt": "2015-03-05T17:06:00.000+0500",
              "nextVisitAt": "2015-03-06T17:06:00.000+0500",
              "state": "COMPLETED",
              "diagnosis": "Ветрянка",
              "treatmentPlan": [{
                "id": 1,
                "title": "Левофлоксацин (Сигницеф,Л-оптик,Офтаквикс)",
                "plan": "1 к х 8 раз в день в оба глаза -3 дня,затем 1 к х 4 разав день - 4 дня"                
              }],
              "researchPlan": "Сдать анализы. Анализы принимаются по будням",
              "researchData": "bla bla bla",
              "status": "Консультация",
              "recommendations": "Рекомендация 1: 456: 789: 123",
              "employee":          {
                    "id": 1,
                    "phone": "79021234567",
                    "position":             {
                        "id": 1,
                        "name": "Терапевт"
                    }
                },
              "price" : 305.12
           },
           {
              "id": 2,
              "visitAt": "2015-03-05T17:06:00.000+0500",
              "nextVisitAt": "2015-03-06T17:06:00.000+0500",
              "state": "COMPLETED",
              "diagnosis": "Мракобесие",
              "treatmentPlan": [{
                "id": 1,
                "title": "Левофлоксацин (Сигницеф,Л-оптик,Офтаквикс)",
                "plan": "1 к х 8 раз в день в оба глаза -3 дня,затем 1 к х 4 разав день - 4 дня"                
              }],
              "researchPlan": "Сдать анализы. Анализы принимаются по будням",
              "researchData": "bla bla bla",
              "status": "Окуривание",
              "recommendations": "Рекомендация 1: 456: 789: 123",
              "employee":          {
                    "id": 1,
                    "phone": "79021234567",
                    "position":             {
                        "id": 1,
                        "name": "Шаман"
                    }
                },
              "price" : 300
           },
           {
              "id": 3,
              "visitAt": "2015-03-05T17:06:00.000+0500",
              "nextVisitAt": "2015-03-06T17:06:00.000+0500",
              "state": "COMPLETED",
              "diagnosis": "ОРВИ",
              "treatmentPlan": [{
                "id": 1,
                "title": "Левофлоксацин (Сигницеф,Л-оптик,Офтаквикс)",
                "plan": "1 к х 8 раз в день в оба глаза -3 дня,затем 1 к х 4 разав день - 4 дня"                
              }],
              "researchPlan": "Сдать анализы. Анализы принимаются по будням",
              "status": "Консультация",
              "recommendations": "Рекомендация 1: 456: 789: 123",
              "employee":          {
                    "id": 1,
                    "phone": "79021234567",
                    "position":             {
                        "id": 1,
                        "name": "Терапевт"
                    }
                },
              "price" : 128.5
           },
           {
              "id": 4,
              "visitAt": "2015-03-05T17:06:00.000+0500",
              "nextVisitAt": "2015-03-06T17:06:00.000+0500",
              "state": "COMPLETED",
              "diagnosis": "Неведомая ерунда",
              "treatmentPlan": [{
                "id": 1,
                "title": "Левофлоксацин (Сигницеф,Л-оптик,Офтаквикс)",
                "plan": "1 к х 8 раз в день в оба глаза -3 дня,затем 1 к х 4 разав день - 4 дня"                
              },
              {
                "id": 2,
                "title": "Test-huest",
                "plan": "1 к х 8 раз в день в оба глаза -3 дня,затем 1 к х 4 разав день - 4 дня"                
              }],
              "researchPlan": "Сдать анализы. Анализы принимаются по будням",
              "status": "Выписка",
              "recommendations": "Рекомендация 1: 456: 789: 123",
              "employee":          {
                    "id": 1,
                    "phone": "79021234567",
                    "position":             {
                        "id": 1,
                        "name": "Специалист по неведомой ерунде"
                    }
                },
              "price" : 512
           }
           ]
        }

## Консультация пациента [/api/patient/consultation/{id}]
### Чтение консультации [GET]

+ Parameters

    + id (required, integer, `1`)

+ Request (application/json)

    + Headers

            X-API-VERSION: v1
            sid: {sid}

+ Response 200 (application/json)

        {
           "success": true,
           "message": "Карточка консультации прочитана успешно!",
           "consultation":    {
              "id": 1,
              "visitAt": "2015-03-06T16:21:00.000+0500",
              "nextVisitAt": "2015-03-06T17:06:00.000+0500",
              "state": "COMPLETED",
              "diagnosis": "Ветрянка",
              "treatmentPlan": [{
                "id": 1,
                "title": "Левофлоксацин (Сигницеф,Л-оптик,Офтаквикс)",
                "plan": "1 к х 8 раз в день в оба глаза -3 дня,затем 1 к х 4 разав день - 4 дня"                
              }],
              "researchPlan": "",
              "researchData": "bla bla bla",
              "status": "Консультация",
              "recommendations": "Рекомендация 1: 456: 789: 123",
              "employee":          {
                    "id": 1,
                    "phone": "79021234567",
                    "position": {
                        "id": 1,
                        "name": "терапевт ревматолог"
                    }
                }
           }
        }
        
##Справочник специализации [/api/catalog/specialisation]
### Чтение [GET]        

+ Request (application/json)

    + Headers

            X-API-VERSION: v1

+ Response 200 (application/json)

        [{
               "id": 1,
               "title": "уролог"
        }]
      
##Компании [/api/company?search={search}]
### Чтение [GET]        

+ Parameters

    + search (optional, string)

+ Request (application/json)

    + Headers

            X-API-VERSION: v1

+ Response 200 (application/json)

        [{
               "id": 1,
               "title": "Шанс"
        }]      

## Аптека [/api/pharmacy/]        
### Чтение заказов на лекарства [GET]

+ Parameters

    + page (required, integer, `0`) ... Страница к отображению
    + size (required, integer, `10`) ... размер страницы для отображения

+ Request (application/json)

    + Headers

            X-API-VERSION: v1
            sid: {sid}

+ Response 200 (application/json)

            [{
                    "id" : 1,
                    "state" : "NEW",//OrderState
                    "createdAt" : '2015-03-05T17:06:00.000+0500',
                    "num": "1-1",
                    "prices" : [
                        {
                            "id":1,
                            "title": "Левофлоксацин (Сигницеф,Л-оптик,Офтаквикс)",
                            "form": "90 таблеток по 50мг",
                            "price": 14212, //в копейках
                            "amount":1
                        },
                        {
                            "id":2,
                            "title": "Подорожник",
                            "form": "50 листочков по 1",
                            "price":, 1000 //в копейках
                            "amount":1
                        },
                        {
                            "id":3,
                            "title": "Амбробене",
                            "form": "150 мл",
                            "price": 18575, //в копейках
                            "amount":1
                        }                    
                    ]
            }]
                  
## Заказы [/api/pharmacy/{id}?latitude={latitude}&longitude={longitude}]
### Чтение цен на лекарства [GET]

+ Parameters

    + id (required, integer, `1`) ... идентификатор консультации
    + latitude (required, double, `60.1`) ... широта пациента
    + longitude (required, double, `60.2`) ... долгота пациента
    + radius (required, double, `1000.0`) ... радиус

+ Request (application/json)

    + Headers

            X-API-VERSION: v1
            sid: {sid}

+ Response 200 (application/json)

        {
               "success": true,
               "message": "Цены прочитаны успешно!",
               "pharmacy": [{
                  "id": 1,
                  "title" : "Живика",
                  "address": "Город екатеринбург, Ленина 105",
                  "latitude": 60.1,
                  "longitude": 60.2,
                  "fullprice": 17116, //в копейках
                  "medicines": [{
                    "id":1,
                    "title": "Левофлоксацин (Сигницеф,Л-оптик,Офтаквикс)",
                    "form": "90 таблеток по 50мг",
                    "price": 15916 //в копейках
                  },
                  {"id":2,
                    "title": "Подорожник",
                    "form": "50 листочков по 1",
                    "price": 1200 //в копейках
                  }]
               },
               {
                  "id": 2,
                  "title" : "36,6",
                  "address": "Город екатеринбург, Ленина 101",
                  "fullprice": 33787, //в копейках
                  "medicines": [{
                    "id":1,
                    "title": "Левофлоксацин (Сигницеф,Л-оптик,Офтаквикс)",
                    "form": "90 таблеток по 50мг",
                    "price": 14212 //в копейках
                  },
                  {"id":2,
                    "title": "Подорожник",
                    "form": "50 листочков по 1",
                    "price": 1000 //в копейках
                  },
                  {"id":3,
                    "title": "Амбробене",
                    "form": "150 мл",
                    "price": 18575 //в копейках
                  }]
               }]
        }
    
### Размещение заявки на лекарства [POST]
+ Parameters

    + id (required, integer, `1`) ... идентификатор консультации

+ Request (application/json)

    + Headers

            X-API-VERSION: v1
            sid: {sid}

    + Body
    
            {
                  prices : [
                    {
                        "id":3, // идентификатор цены, например амбробене
                        "amount":1 //Количество препарата
                    }, 
                    {
                        "id":1,
                        "amount":1
                    },
                  ]
            } 

+ Response 200 (application/json)

        {
               "success": true,
               "message": "Заказ успешно размещен. Ожидайте звонка",
               "order" : {
                    "id" : 1,
                    "state" : "NEW",//OrderState
                    "num": "1-1",
                    "prices" : [
                        {
                            "id":1,
                            "title": "Левофлоксацин (Сигницеф,Л-оптик,Офтаквикс)",
                            "form": "90 таблеток по 50мг",
                            "price": 14212, //в копейках
                            "amount":1
                        },
                        {
                            "id":2,
                            "title": "Подорожник",
                            "form": "50 листочков по 1",
                            "price":, 1000 //в копейках
                            "amount":1
                        },
                        {
                            "id":3,
                            "title": "Амбробене",
                            "form": "150 мл",
                            "price": 18575, //в копейках
                            "amount":1
                        }                    
                    ]
               }
        }